### ISSUE TITLE
Monitor multiple users

### ISSUE THREAD

**Issue by ikoiko12** [misiektoja/instagram_monitor#1]
Hello. Thanks, it's a pretty good tool. I can't figure it out and can you help me monitor some users, how can I do it?

**Comment by misiektoja** [comment]
Hey,

To monitor multiple Instagram users simply spawn additional copies of the script. If you are doing this on your desktop simply open separate terminal windows and in the first one monitor the first user:

```./instagram_monitor.py user1```

and in the second:

```./instagram_monitor.py user2```

However I recommend to use sth like tmux or screen (not sure which OS you are using):

Create tmux session for first user:

```tmux new -s insta_user1```

Then run the tool for the first user:

```./instagram_monitor.py user1```

Press Ctrl+B and then D to detach from the session.

Then create tmux session for second copy of the script:

```tmux new -s insta_user2```

And run the tool for the second user:

```./instagram_monitor.py user2```

You can reattach to the sessions created earlier like this

```tmux a -t insta_user1```

```tmux a -t insta_user2```
