### ISSUE TITLE
f-string syntax errors on Trace Labs Kali distro

### ISSUE THREAD

**Issue by kiing98** [misiektoja/instagram_monitor#2]
I have to follow private accounts in order to monitorate or no?

**Comment by misiektoja** [comment]
Hi, just an answer: no, you don't have to follow the private user (however it gives you some perks if you do and get your follow request accepted ;-)).

**Comment by kiing98** [comment]
Im having this following issue, can u help me?

![Screenshot_2024-063333_00-07-14](https://github.com/misiektoja/instagram_monitor/assets/172418071/02c7ada5-57ca-4f09-8c03-343dd1231eec)

**Comment by misiektoja** [comment]
Hmm, interesting. What version of Python do you have installed ?

```
python --version
```

Can you meanwhile check the dev version of the script I just pushed to the repo ? 

https://github.com/misiektoja/instagram_monitor/blob/dev/instagram_monitor.py

**Comment by kiing98** [comment]
Im running 3.11.9.

I tested the dev version! Now I can run 'python3 ./instagram_monitor.py -h` but now I have a new error lol, look. any thoughts ?

![1](https://github.com/misiektoja/instagram_monitor/assets/172418071/ab5ba5af-bc03-451c-be92-dc929090cb87)

![2](https://github.com/misiektoja/instagram_monitor/assets/172418071/134043e9-cd3b-4f65-8503-56376a7b476c)

Tks! :))))

**Comment by misiektoja** [comment]
Ok, let me install Python 3.11 and I will get back to you with fixed version shortly. 

It seems I need to fix all my tools ;-)

**Comment by kiing98** [comment]
> Ok, let me install Python 3.11 and I will get back to you with fixed version shortly. 
> 
> 
> 
> It seems I need to fix all my tools ;-)

Thanks for your support! I did not mean to bring you trouble and work D: sorry for that

**Comment by misiektoja** [comment]
Haha, all is good, don't worry ;-) 

Honestly, I have no clue why it does not work in your env. What OS do you have ? Windows ? Which version?

I installed Python 3.11.9, everything works in my case. Cannot replicate it. I also checked few code linters - also good. So idk why it complains in your case, even though I understand from where the issue comes from.

Anyway, check the newest dev version of the tool, it should be good now:

https://github.com/misiektoja/instagram_monitor/blob/dev/instagram_monitor.py

**Comment by kiing98** [comment]
Thanks!

Actually i`m running Trace Labs VM, kali distro.
What OS you recommend I run it?

Also, I will try to update my python to 3.12 and see if it works.

About the new dev version, new error, now on line 637 again.
Really dont know what im doing wrong, on login, I used instaloader but also put the username on instragram_monitor.py (but I left password blank).

Also, I did not put email info. Any thoughts?

**Comment by misiektoja** [comment]
It should run just fine under Kali, however I have never tested version from Trace Labs. 

Let me download it as now you got me really curious why it does not run there ;-)

**Comment by MohamedEHJ** [comment]
Same issue, i'm using Python 3.10.12
```  
File "/home/bibop/mes_apps/instagram_monitor/./instagram_monitor.py", line 385
    return (f"{ts_str}{calendar.day_abbr[(datetime.fromtimestamp(int(time.time()))).weekday()]}, {datetime.fromtimestamp(int(time.time())).strftime("%d %b %Y, %H:%M:%S")}")

                             ^
SyntaxError: f-string: unmatched '('
```

**Comment by misiektoja** [comment]
I just merged changes from dev to main branch. Download the file again and it should be ok.

**Comment by MohamedEHJ** [comment]
yup using instagram_monitor.py from dev branch solved the issue.
Nice work btw!

**Comment by kiing98** [comment]
> I deployed Trace Labs version of Kali Linux in my lab and indeed got the same issues. Strange, but anyway check out the newest dev version of the tool, it should work now.
> 
> Quick install instructions for Kali Linux:
> 
> ```
> git clone -b dev https://github.com/misiektoja/instagram_monitor/
> cd instagram_monitor
> pip3 install -r requirements.txt
> ```
> 
> First check with mode 1 (no session login):
> 
> ```
> python3 instagram_monitor.py instagram_user_you_want_to_monitor
> ```
> 
> If all is good then give it a try with mode 2 (with session login):
> 
> ```
> instaloader -l your_instagram_account
> python3 instagram_monitor.py -u your_instagram_account instagram_user_you_want_to_monitor
> ```

Yesssssssss! Solved!
I`d like to thank you for your support, Instagram Monitor working just fine now!
In case I come across new erros I`ll report it to you in order to help ppl .

Question: I can see new posts and stories using mode 1 and mode 2, ok for public profile. But as soon as I private my personal profile (used for testing) I can no longer see new updates. So does this only work with public profiles? I mean, I can't monitor private profiles that I don't follow?

Thanks!

**Comment by kiing98** [comment]
> I deployed Trace Labs version of Kali Linux in my lab and indeed got the same issues. Strange, but anyway check out the newest dev version of the tool, it should work now.
> 
> Quick install instructions for Kali Linux:
> 
> ```
> git clone -b dev https://github.com/misiektoja/instagram_monitor/
> cd instagram_monitor
> pip3 install -r requirements.txt
> ```
> 
> First check with mode 1 (no session login):
> 
> ```
> python3 instagram_monitor.py instagram_user_you_want_to_monitor
> ```
> 
> If all is good then give it a try with mode 2 (with session login):
> 
> ```
> instaloader -l your_instagram_account
> python3 instagram_monitor.py -u your_instagram_account instagram_user_you_want_to_monitor
> ```

Yesssssssss! Solved!

Id like to thank you for your support, Instagram Monitor working just fine now! In case I come across new erros Ill report it to you in order to help ppl .

Question: I can see new posts and stories using mode 1 and mode 2, ok for public profile. But as soon as I private my personal profile (used for testing) I can no longer see new updates. So does this only work with public profiles? I mean, I can't monitor private profiles that I don't follow?

Thanks!

**Comment by misiektoja** [comment]
The tool works with private Instagram accounts, but with some limitations.

Obviously we cannot get all the details (like contents of stories or posts/reels), but you can still get a lot of useful OSINT details which you can relate to date/time.

Some things are available easilly even with private profiles, so with the tool you will know when the bio or profile picture changes for the user.

Some things are partially available, so for example you will be still informed when follower/followings number changes, but you won't know which followers/followings have been added/removed (as it is a private profile).

The same applies to new posts/reels. The tool will notice when the number of posts/reels changes, so you will know that user created (or removed) a post, but you won't be able to see its contents (since it is private profile). 

So you can still get some info, but clearly not everything as for public profiles. 

Anyway, for private profiles it is recommended to use mode 1 as it is resistant to Instagram's automated tool detection mechanisms (and mode 2 does not give you any additional info in case of private profiles).

**Comment by kiing98** [comment]
> The tool works with private Instagram accounts, but with some limitations.
> 
> Obviously we cannot get all the details (like contents of stories or posts/reels), but you can still get a lot of useful OSINT details which you can relate to date/time.
> 
> Some things are available easilly even with private profiles, so with the tool you will know when the bio or profile picture changes for the user.
> 
> Some things are partially available, so for example you will be still informed when follower/followings number changes, but you won't know which followers/followings have been added/removed (as it is a private profile).
> 
> The same applies to new posts/reels. The tool will notice when the number of posts/reels changes, so you will know that user created (or removed) a post, but you won't be able to see its contents (since it is private profile).
> 
> So you can still get some useful info for private profiles, but obviously not everything as in case of public profiles.
> 
> Anyway, for private profiles it is recommended to use mode 1 as it is resistant to Instagram's automated tool detection mechanisms (and mode 2 does not give you any additional info in case of private profiles).

Perfet explanation!
I will do good use of it. Again, thanks for your work and great support.

Following you for your next good ideas.

Thanks, @misiektoja!

Best regards.
